name: Build OpenModParty

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore OpenModParty.csproj
      - name: Build
        run: dotnet build OpenModParty.csproj -c Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenModPartyBuild
          path: bin/Release/net8.0/**
